### ISSUE TITLE
Uncaught TypeError: Not a string or buffer

### ISSUE THREAD

**Issue by Pondidum** [s-shin/atom-copy-path#2]
[Enter steps to reproduce below:]
1. create a new file
2. save it
3. right click the tab, "Copy Full Path"

**Atom Version**: 1.0.11
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [copy-path](https://github.com/s-shin/atom-copy-path) package, v0.1.1
### Stack Trace

Uncaught TypeError: Not a string or buffer

```
At crypto.js:97

TypeError: Not a string or buffer
    at TypeError (native)
    at Hash.update (crypto.js:97:16)
    at Clipboard.module.exports.Clipboard.md5 (C:\Users\Andy\AppData\Local\atom\app-1.0.11\resources\app.asar\src\clipboard.js:16:39)
    at Clipboard.module.exports.Clipboard.write (C:\Users\Andy\AppData\Local\atom\app-1.0.11\resources\app.asar\src\clipboard.js:20:40)
    at _class.copyFullPath (C:/Users/Andy/.atom/packages/copy-path/lib/index.js:79:20)
    at atom-workspace.copyPathCopyFullPath (C:/Users/Andy/.atom/packages/copy-path/lib/index.js:18:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Andy\AppData\Local\atom\app-1.0.11\resources\app.asar\src\command-registry.js:245:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Andy\AppData\Local\atom\app-1.0.11\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Andy\AppData\Local\atom\app-1.0.11\resources\app.asar\src\command-registry.js:156:19)
    at [object Object].jQuery.fn.trigger (C:\Users\Andy\AppData\Local\atom\app-1.0.11\resources\app.asar\src\space-pen-extensions.js:64:23)
```
### Commands

```
     -0:16.9.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:14.8.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "wrap-guide"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
copy-path, v0.1.1
file-types, v0.5.1
project-manager, v2.2.0

# Dev
No dev packages
```

**Comment by fweber-de** [comment]
@s-shin i will look into this when i am at work tomorrow on a win 7 machine

**Comment by fweber-de** [comment]
@Pondidum @s-shin sorry i cant reproduce this behaviour on Windows 7 Pro

**Comment by Pondidum** [comment]
I've just tried again on my work machines (where I had the issue originally), and it no longer happens - I assume an atom or copy-path update has fixed it, so closing this issue.

**Comment by s-shin** [comment]
Great! Thank you for your working.

**Comment by theurge14** [comment]
I am still encountering this issue, it doesn't happen when I first open Atom but after 10-15 minutes of working this issue comes up.  I have to restart Atom to clear the error.

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [copy-path](https://github.com/s-shin/atom-copy-path) package, v0.4.0

### Stack Trace

Uncaught TypeError: Not a string or buffer

```
At crypto.js:70

TypeError: Not a string or buffer
    at TypeError (native)
    at Hash.update (crypto.js:70:16)
    at Clipboard.module.exports.Clipboard.md5 (C:\Users\cboyd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\clipboard.js:19:39)
    at Clipboard.module.exports.Clipboard.write (C:\Users\cboyd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\clipboard.js:23:40)
    at _class.copyFullPath (C:/Users/cboyd/.atom/packages/copy-path/lib/index.js:123:20)
    at atom-workspace.copyPathCopyFullPath (C:/Users/cboyd/.atom/packages/copy-path/lib/index.js:18:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\cboyd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\cboyd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\cboyd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\cboyd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\atom-environment.js:1106:28)
    at EventEmitter.outerCallback (C:\Users\cboyd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\application-delegate.js:327:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
     -0:23.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:20.1.0 copy-path:copy-full-path (div.title)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "spell-check",
      "wrap-guide",
      "copy-filename"
    ],
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
copy-path, v0.4.0
language-cisco, v1.4.0
minimap, v4.22.1
nucleus-dark-ui, v0.7.16

# Dev
No dev packages
```
