### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by s-shin** [s-shin/atom-copy-path#21]
1. Open a new tab by `Cmd+N`.
2. `Copy Basename` from the context menu on any tab.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [copy-path](https://github.com/s-shin/atom-copy-path) package 0.4.2

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.parse (path.js:1494:5)
    at _class.parseTargetEditorPath (/packages/copy-path/lib/index.js:107:17)
    at _class.copyBasename (/packages/copy-path/lib/index.js:116:25)
    at HTMLElement.copyPathCopyBasename (/packages/copy-path/lib/index.js:14:46)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1290:25)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:346:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:06.0 application:new-file (input.hidden-input)
     -0:01.4.0 copy-path:copy-basename (div.title)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-ruby 1.6.1 
atom-color-highlight 3.0.9 
atom-ctags 5.1.2 
atom-fuzzy-grep 0.17.2 
atom-ternjs 0.18.3 
atom-typescript 12.1.2 
autocomplete-clang 0.11.4 
autocomplete-paths 2.12.2 
blame 1.0.1 
block-travel 1.0.5 
busy-signal 1.4.3 
clang-format 1.30.0 
color-picker 2.2.5 
copy-path 0.4.2 
docblockr 0.13.6 
environment 1.3.1 
ex-mode 0.18.0 
file-icons 2.1.16 
go-debug 1.6.0 
go-plus 5.8.2 
go-signature-statusbar 1.2.3 
highlight-column 0.5.4 
highlight-selected 0.13.1 
hyperclick 0.1.5 
indent-toggle-on-paste 0.1.3 
intentions 1.1.5 
jumpy 4.2.0 
language-apache 1.8.0 
language-bison 1.0.0 
language-cmake 1.1.0 
language-haskell 1.17.3 
language-jade 0.7.2 
language-kotlin 0.5.0 
language-plantuml 0.2.0 
language-protobuf 0.7.1 
language-rust 0.4.12 
language-scala 1.1.9 
language-vue 0.23.1 
linter 2.2.0 
linter-clang 4.1.2 
linter-coffeelint 1.3.1 
linter-eslint 8.4.1 
linter-jsxhint 0.1.2 
linter-kotlin 0.6.0 
linter-perl 0.8.1 
linter-perl-lint 0.1.2 
linter-perl-misc 0.1.1 
linter-rubocop 2.2.3 
linter-scalac 1.4.4 
linter-shellcheck 1.4.6 
linter-tslint 1.9.0 
linter-ui-default 1.6.10 
local-settings 0.4.1 
merge-conflicts 1.4.5 
minesweeper 0.1.0 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-pigments 0.2.2 
pigments 0.40.2 
pomodoro 1.2.0 
preview 0.17.0 
react 0.17.0 
rubocop-auto-correct 1.5.1 
script 3.17.3 
starred-projects 0.1.0 
stealth-mode 0.0.0 
tag 0.5.0 
terminal-plus 0.14.5 
todo-show 2.1.0 
toggle-quotes 1.1.0 
upload 0.0.0 
vim-mode 0.66.0 
vim-mode-plus 1.28.0 
```

**Comment by s-shin** [comment]
Fixed by https://github.com/s-shin/atom-copy-path/pull/22.
