### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by nicekei** [s-shin/atom-copy-path#4]
[Enter steps to reproduce below:]

it just happens.
1. cmd +t
2. select a file
3. right mouse click and select copy project relative path

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [copy-path](https://github.com/s-shin/atom-copy-path) package, v0.2.1
### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/kei/.atom/packages/copy-path/lib/index.js:48

TypeError: Cannot read property 'getPath' of undefined
    at _class.getTargetEditorPath (/Users/kei/.atom/packages/copy-path/lib/index.js:48:48)
    at _class.copyProjectRelativePath (/Users/kei/.atom/packages/copy-path/lib/index.js:76:59)
    at atom-workspace.copyPathCopyProjectRelativePath (/Users/kei/.atom/packages/copy-path/lib/index.js:17:59)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:993:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:138:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:252:47)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -2:56.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:53.9.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -2:53.6.0 core:copy (atom-text-editor.editor.is-focused)
  6x -2:53.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:51.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -2:50.4.0 core:paste (atom-text-editor.editor.is-focused)
     -2:49.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:47.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:47.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -2:46.9.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -2:29.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:12.7.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:56.2.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:51.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:01.2.0 copy-path:copy-project-relative-path (li.tab.sortable.active.right-clicked)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
copy-path, v0.2.1

# Dev
No dev packages
```

**Comment by nicekei** [comment]
In short, not work with images(eg. jpeg)
